---
kind: pipeline
type: docker
name: docker-build

steps:
  - name: docker
    image: plugins/kaniko:1.7.1-kaniko1.9.1
    settings:
      repo: 15cm/flaresolverr
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  branch:
    - master
    - v3beta
  event:
    - push
    - custom
    - tag
